### ISSUE TITLE
Kannst du bei Twitter einstellen, dass man dir eine DM schreiben kann

### ISSUE THREAD

**Issue by Filler-dev** [CodeCLS/Lemon-Markets-Java-SDK#16]
Kannst du bei Twitter einstellen, dass man dir eine DM schreiben kann. Habe nämlich paar Fragen hierzu

**Comment by CodeCLS** [comment]
Hey Filler-dev, meine dms sind offen. Schreib mir(@CodingCaleb) oder per Email: primocaleb@gmail.com

**Comment by Filler-dev** [comment]
Hattest dann in deiner Readme Datei einen anderen Namen auf deiner Profilseite

**Comment by CodeCLS** [comment]
Ups. Ändere ich sobald ich kann, danke für die Info.
